2022-04-26 14:13:37,609 INFO    Thread-39 :2545573 [wandb_setup.py:_flush():75] Loading settings from /home/rishabh/.config/wandb/settings
2022-04-26 14:13:37,609 INFO    Thread-39 :2545573 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-04-26 14:13:37,609 INFO    Thread-39 :2545573 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'entity': 'rish-16', 'project': 'cs4243-project', 'root_dir': '/home/rishabh/practice_runs/cs4243-project', 'run_id': 'uop6fbh8', 'sweep_param_path': '/home/rishabh/practice_runs/cs4243-project/wandb/sweep-nmt99lp3/config-uop6fbh8.yaml', 'sweep_id': 'nmt99lp3'}
2022-04-26 14:13:37,609 INFO    Thread-39 :2545573 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-26 14:13:37,609 INFO    Thread-39 :2545573 [wandb_init.py:_log_setup():437] Logging user logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_141337-uop6fbh8/logs/debug.log
2022-04-26 14:13:37,609 INFO    Thread-39 :2545573 [wandb_init.py:_log_setup():438] Logging internal logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_141337-uop6fbh8/logs/debug-internal.log
2022-04-26 14:13:37,610 INFO    Thread-39 :2545573 [wandb_init.py:init():471] calling init triggers
2022-04-26 14:13:37,610 INFO    Thread-39 :2545573 [wandb_init.py:init():475] wandb.init called with sweep_config: {'channel_combos': [64, 256, 512], 'dropout': 0.3, 'epochs': 20, 'hidden_dim': 128, 'learning_rate': 0.02198540957976377}
config: {}
2022-04-26 14:13:37,610 INFO    Thread-39 :2545573 [wandb_init.py:init():524] starting backend
2022-04-26 14:13:37,610 INFO    Thread-39 :2545573 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-26 14:13:37,619 INFO    Thread-39 :2545573 [backend.py:ensure_launched():217] starting backend process...
2022-04-26 14:13:37,721 INFO    Thread-39 :2545573 [backend.py:ensure_launched():222] started backend process with pid: 2546923
2022-04-26 14:13:37,722 INFO    Thread-39 :2545573 [wandb_init.py:init():533] backend started and connected
2022-04-26 14:13:37,741 INFO    Thread-39 :2545573 [wandb_run.py:_config_callback():1131] config_cb None None {'channel_combos': [64, 256, 512], 'dropout': 0.3, 'epochs': 20, 'hidden_dim': 128, 'learning_rate': 0.02198540957976377}
2022-04-26 14:13:37,745 INFO    Thread-39 :2545573 [wandb_run.py:_label_probe_notebook():1084] probe notebook
2022-04-26 14:13:37,746 INFO    Thread-39 :2545573 [wandb_init.py:init():597] updated telemetry
2022-04-26 14:13:37,955 INFO    Thread-39 :2545573 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-04-26 14:13:38,763 INFO    Thread-39 :2545573 [wandb_run.py:_on_init():1923] communicating current version
2022-04-26 14:13:38,817 INFO    Thread-39 :2545573 [wandb_run.py:_on_init():1927] got version response 
2022-04-26 14:13:38,817 INFO    Thread-39 :2545573 [wandb_init.py:init():659] starting run threads in backend
2022-04-26 14:13:39,419 INFO    MainThread:2545573 [wandb_init.py:_pause_backend():350] pausing backend
2022-04-26 14:13:39,419 INFO    MainThread:2545573 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-04-26 14:13:39,507 ERROR   Thread-39 :2545573 [wandb_init.py:init():1022] error
Traceback (most recent call last):
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 995, in init
    run = wi.init()
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 670, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 221, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 440, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/rishabh/miniconda3/envs/Rish4243/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/rishabh/miniconda3/envs/Rish4243/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2022-04-26 14:15:20,361 INFO    MainThread:2545573 [wandb_init.py:_resume_backend():359] resuming backend
2022-04-26 14:15:20,374 INFO    MainThread:2545573 [wandb_init.py:_pause_backend():350] pausing backend
2022-04-26 14:15:20,374 INFO    MainThread:2545573 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-04-26 14:15:53,551 INFO    MainThread:2545573 [wandb_init.py:_resume_backend():359] resuming backend
2022-04-26 14:15:53,565 INFO    MainThread:2545573 [wandb_init.py:_pause_backend():350] pausing backend
2022-04-26 14:15:53,566 INFO    MainThread:2545573 [jupyter.py:save_ipynb():377] not saving jupyter notebook
